# Generated by Django 4.0.3 on 2022-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_complaints_department_alter_complaints_panchayath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('uname', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('announcement', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='complaints',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
