# Generated by Django 4.0.3 on 2022-04-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_announcement_alter_complaints_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='panchayath',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
