# Generated by Django 4.0.3 on 2022-04-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_announcement_panchayath'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='username',
            field=models.CharField(default='x', max_length=30),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='panchayath',
            field=models.CharField(max_length=100),
        ),
    ]
