# Generated by Django 4.0.3 on 2022-04-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_vote_username_alter_announcement_panchayath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='uid',
            new_name='userid',
        ),
        migrations.AlterField(
            model_name='vote',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
