# Generated by Django 4.0.3 on 2022-04-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_uid_vote_userid_alter_vote_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
