# Generated by Django 4.0.3 on 2022-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_vote_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='panchayath',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
