# Generated by Django 4.0.3 on 2022-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_message_panchayath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='uid',
        ),
        migrations.AddField(
            model_name='message',
            name='receiverid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='senderid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='panchayath',
            field=models.CharField(max_length=100),
        ),
    ]
