# Generated by Django 4.0.3 on 2022-04-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_message_uid_message_receiverid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='uname',
        ),
        migrations.AddField(
            model_name='message',
            name='receivername',
            field=models.CharField(default='x', max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='sendername',
            field=models.CharField(default='x', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiverid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='senderid',
            field=models.IntegerField(),
        ),
    ]
