# Generated by Django 4.0.3 on 2022-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_message_uname_message_receivername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(db_column='m1', max_length=300),
        ),
        migrations.AlterField(
            model_name='message',
            name='receivername',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='sendername',
            field=models.CharField(max_length=30),
        ),
    ]
