# Generated by Django 4.0.3 on 2022-04-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_message_message_alter_message_receivername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, db_column='m1', max_length=300, null=True),
        ),
    ]
