# Generated by Django 4.0.3 on 2022-04-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
