# Generated by Django 4.0.3 on 2022-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creatorid',
            field=models.IntegerField(),
        ),
    ]
