# Generated by Django 4.0.3 on 2022-04-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_post_pimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-postid']},
        ),
    ]
