# Generated by Django 4.0.3 on 2022-04-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_rename_pimage_post_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-aid']},
        ),
        migrations.AlterModelOptions(
            name='complaints',
            options={'ordering': ['-cid']},
        ),
    ]
