# Generated by Django 4.0.3 on 2022-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_photo_post_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pimage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
