# Generated by Django 4.0.3 on 2022-04-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentator',
            field=models.CharField(default='x', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
