# Generated by Django 4.0.3 on 2022-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_post_commentator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentid', models.IntegerField()),
                ('commentatorid', models.IntegerField()),
                ('commentator', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='commentator',
        ),
    ]
