# Generated by Django 4.0.3 on 2022-04-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_comments_remove_post_comment_remove_post_commentator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
