# Generated by Django 4.0.3 on 2022-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_remove_comments_id_alter_comments_commentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentcount',
            field=models.IntegerField(default=0),
        ),
    ]
