# Generated by Django 4.0.3 on 2022-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_post_commentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='postid',
            field=models.IntegerField(default=0),
        ),
    ]
