# Generated by Django 4.0.3 on 2022-05-01 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_comments_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 19, 1, 8, 872561)),
        ),
        migrations.AddField(
            model_name='announcement',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 19, 1, 8, 872561)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='announcement',
            field=models.TextField(default='x', max_length=300),
        ),
        migrations.AlterField(
            model_name='comments',
            name='postid',
            field=models.IntegerField(),
        ),
    ]
