# Generated by Django 4.0.3 on 2022-05-01 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_announcement_created_announcement_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 5, 1, 20, 1, 52, 507654)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2022, 5, 3, 20, 1, 52, 507654)),
        ),
    ]
