# Generated by Django 4.0.3 on 2022-05-02 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_post_panchayath_alter_announcement_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 5, 2, 9, 36, 22, 404970)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 9, 36, 22, 404970)),
        ),
        migrations.AlterField(
            model_name='post',
            name='panchayath',
            field=models.CharField(max_length=40),
        ),
    ]
