# Generated by Django 4.0.3 on 2022-05-08 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_alter_announcement_created_alter_announcement_expiry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-mid']},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 5, 8, 13, 47, 43, 734916)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2022, 5, 10, 13, 47, 43, 734916)),
        ),
    ]
