from django.urls import path
from .views import UserCreateView, DepartmentListView, DepartmentCreateView, Editprofile, EditprofileDept
from myapp import views

urlpatterns = [
    path('', views.loginpage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('user/', UserCreateView.as_view(), name='user-reg'),
    path('dept/', DepartmentCreateView.as_view(), name='dept-reg'),
    path('list/', DepartmentListView.as_view(), name='list'),
    path('approval/<int:did>', views.DepartmentApprove),
    path('rejection/<int:did>', views.DepartmentReject),
    path('post/', views.post, name='post'),
    path('postdept/', views.postdept, name='postdept'),
    path('display/', views.displayPost, name='display'),
    path('displaydept/', views.displayPostDept, name='displaydept'),
    path('change/', views.changePasswordUser, name='change'),
    path('upvote/<int:postid>', views.upvote, name='upvote'),
    path('downvote/<int:postid>', views.downvote, name='downvote'),
    path('neighbours/', views.neighbours, name='neighbours'),
    path('people/', views.people, name='people'),
    path('complaints/', views.complaints, name='complaints'),
    path('complaintlist/', views.complaintList, name='complaintlist'),
    path('settings/', views.settings, name='settings'),
    path('settingsdept/', views.settingsdept, name='settingsdept'),
    path('profile/', views.profileuser, name='profile'),
    path('peopleprofile/<str:username>', views.peopleProfile, name='peopleprofile'),
    path('profiledept/', views.profiledept, name='profiledept'),
    path('announcement/', views.announcement, name='announcement'),
    path('announcementlist/', views.announcementlist, name='announcementlist'),
    path('message/', views.messagepage, name='message'),
    path('messagepost/<int:uid>/<str:username>', views.messagepost, name='messagepost'),
    path('delete/<int:postid>/', views.delete, name='delete'),
    path('update/<int:postid>/', views.update, name='delete'),
    path('comments/<int:postid>/', views.comments, name='comments'),
    path('deletecomment/<int:commentid>/<int:postid>/', views.deleteComment, name='deletecomment'),
    path('editprofile/<pk>', Editprofile.as_view(), name='editprofile'),
    path('editprofiledept/<pk>', EditprofileDept.as_view(), name='editprofiledept'),
    # path('refresh/', views.refresh, name='refresh'),
    path('searchbar/', views.searchbar, name='searchbar'),
    path('searchbardept/', views.searchbardept, name='searchbardept'),
    path('adminhome/', views.adminhome, name='adminhome'),

]
